# Generated by Django 6.0.5 on 2026-06-23 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_timesstamp',
            new_name='created_timestamp',
        ),
    ]
